### PR TITLE
containers: fixed templates for MSVC compiler compliancy

### PR DESCRIPTION
**Pull request by roccoarpa**
The following pull adjusts nomenclature of some templates methods to achieve compliancy with MSVC cl compiler. They do not fix errors in the gnu context, they simply reword methods in an alternative way.

Main mods involve the PiercedStorage/PiercedVector classes (see commits description).

Additionally, rewording on some preprocessor macro was needed (see commit description)

### CODE REVIEW

**Comment by roccoarpa** [comment]
Failure on travis build depends on a problem on clang compiler on usage of EnableArgsInitType in template (missing typename). The problem is clang only: code compiles fine on gnu gcc (4.8, 7.3, 9.3) and msvc-vs 2019. Need to investigate more.

**Comment by roccoarpa** [comment]
commit  https://github.com/optimad/bitpit/pull/282/commits/5611d3730b0703e224e97913678d658b99506d26 partially reworks  commit https://github.com/optimad/bitpit/pull/282/commits/f0c43b485b904364c8e30ff8c5ff79fbdb490364 to recover compliancy with clang compilers  (works on clang 7.0.1 and 10.0.0). 
I know, the 2 should be squashed, but i'm waiting for CI response first.

**Comment by roccoarpa** [comment]
squashed abovementioned commits after successfull CI.

**Review by andrea-iob — APPROVED** [review]
Changes look fine.

I've updated a couple of comments and renamed EnableArgsInitType to EnableIfHasInitialize.

**Pull request merged**
