### PR TITLE
patchkernel: fix incorrect id conversions

### PR DESCRIPTION
**Pull request by DMurataj01**

### CODE REVIEW

**Review by andrea-iob — APPROVED** [review]
Changes look good. May I ask you to squash the last two commits together and, for consistency with the current git history, use the format "patchkernel: ..." for the commit messages? Thanks.

**Comment by DMurataj01** [comment]
> Changes look good. May I ask you to squash the last two commits together and, for consistency with the current git history, use the format "patchkernel: ..." for the commit messages? Thanks.

Noted for next time, 
@andrea-iob Are you able to just squash merge & update the commit msg that way for now?

**Comment by andrea-iob** [comment]
I don't think I can do that directly, because the merge request comes from a repository I don't have write access to. I'll find a way.

**Comment by andrea-iob** [comment]
Superseded by #342.

**Pull request closed without merging**
