### PR TITLE
 patchkernel: add a function to check if factes of surface patch have a consistent orientation

### PR DESCRIPTION
**Pull request by andrea-iob**
The function can be used to check if all the factes of a surface patch are oriented in the same way. 

Draft because it need more testing.

### CODE REVIEW

**Comment by andrea-iob** [comment]
I fixed a problem with detection of surface consistency in parallel.

**Review by marcocisternino — APPROVED** [review]
No problems in both serial and up to 36 numbers of cores runs, on several considered geometries

**Comment by andrea-iob** [comment]
@marcocisternino Can you approve the pull request?

**Review by marcocisternino — APPROVED** [review]

**Comment by marcocisternino** [comment]
I was waiting for the pull to be confirmed for review, but I did it

**Pull request merged**
