### PR TITLE
IO/VTK: add support for writing time series 

### PR DESCRIPTION
**Pull request by andrea-iob**
The VTK class is now able to write [PVD files](https://vtk.org/Wiki/ParaView/Data_formats#PVD_File_Format) containing the  information about the time series.

### CODE REVIEW

**Comment by ksamouchos** [comment]
There is a typo in the comment of commit [f769f3a](https://github.com/optimad/bitpit/pull/432/commits/f769f3a0b660853b1c757adeb77dfffc9bab1156) :

"return an invalid counter **is** a file is not in a time series"

**Comment by andrea-iob** [comment]
> There is a typo in the comment of commit [f769f3a](https://github.com/optimad/bitpit/pull/432/commits/f769f3a0b660853b1c757adeb77dfffc9bab1156) :
> 
> "return an invalid counter **is** a file is not in a time series"

Fixed.

**Comment by andrea-iob** [comment]
I've fixed the generation of PVD collection for parallel cases.

**Review by ksamouchos — APPROVED** [review]
The commit history was very helpful. The code was tested by running immerflow branch of pull request https://github.com/optimad/immerflow/pull/747 .

**Pull request merged**
