### PR TITLE
patchkernel: fix sorting of vertices

### PR DESCRIPTION
**Pull request by andrea-iob**
There were two problems with vertex ordering:
 - it is not possible to use a tolerance when sorting points, otherwise the final result will depend from the initial order. To identify the order of the two points, their coordinates will now be compared without any tolerance. However, before comparing the coordinates, it is necessary to check if the two points are coincident within the specified tolerance;
 - for polyhedral elements, the list of vertices should contain the vertices sorted in the same order they first appear in the face stream. This guarantees that vertices will be sorted in the same order regardless of the id of the vertices. In this way given an element, the list of its vertices generated by different processes will iterate the vertices in the same order.

### CODE REVIEW

**Review by roccoarpa — APPROVED** [review]
everything is ok for me.

**Comment by roccoarpa** [comment]
@andrea-iob is it possible to quickly merge this pull?

**Comment by roccoarpa** [comment]
Hello @andrea-iob, always me. I don't know if there is something else going on about this pull, but if not, can we merge it? Let me know.

**Comment by andrea-iob** [comment]
Merged.

**Pull request merged**
